import { Component, OnInit, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-terms-of-service',
  templateUrl: './terms-of-service.page.html',
  styleUrls: ['./terms-of-service.page.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class TermsOfServicePage implements OnInit {

  htmlStr: string = '';
  language = 'Indonesian';

  constructor() { }

  ngOnInit() {
    if(this.language === 'English'){
      this.htmlStr = '<h2><strong><span style="color: #ff6600;">Terms of Service</span></strong></h2>\
      <p><strong>&nbsp;</strong></p>\
      <p><span style="color: #ff6600;"><strong>Terms of Use</strong></span></p>\
      <p><span style="font-weight: 400;">PLEASE CHECK YOUR &ldquo;Foodle&rdquo; TERMS AND CONDITIONS AND PRIVACY POLICY CAREFULLY BEFORE DOWNLOADING THE APPLICATION OR USING Foodle\'s SERVICES FOR THE FIRST TIME.</span></p>\
      <p><span style="font-weight: 400;">By downloading, accessing and / or using the Foodle Application ("Application"), you agree that you have read, understood carefully and comply with these terms of use ("Terms of Use"). These Terms of Use constitute a legal agreement between you and PT Perusahaan Indo Pasifik in connection with your visit, access and use of the Services and Applications (input defined below) and the Foodle website at www.foodle.id ("Website").</span></p>\
      <p><span style="font-weight: 400;">IF YOU DO NOT AGREE, WHETHER SOME OR ALL OF THESE TERMS OF USE, THEN YOU SHOULD NOT ACCESS AND USE THE SERVICES AND APPLICATIONS.</span></p>\
      <p>&nbsp;</p>\
      <p><span style="color: #ff6600;"><strong>General requirements</strong></span></p>\
      <p><span style="font-weight: 400;">PT Perusahaan Indo Pasifik is a company established under the laws of the Republic of Indonesia ("Foodle").</span></p>\
      <p><span style="font-weight: 400;">This application is a software application that functions as a means of purchasing the products provided in the application. This application offers information about the services offered by Foodle. The types of services that Foodle provide through the application are:</span></p>\
      <ul>\
      <li style="font-weight: 400;"><span style="font-weight: 400;">Purchase of products registered in the Application;</span></li>\
      <li style="font-weight: 400;"><span style="font-weight: 400;">Delivery of products purchased via the Application;</span></li>\
      <li style="font-weight: 400;"><span style="font-weight: 400;">Other services that Foodle can add from time to time. (hereinafter referred to as "Services").</span></li>\
      </ul>\
      <p><br /><span style="font-weight: 400;">Foodle has its own and complete policy to reject any of your requests for the Service. Foodle also has its own policy for corrections, accepting directions provided by the Application.</span></p>\
      <p><span style="font-weight: 400;">Foodle will make all efforts for you to get the Service, depending on the product data or the location where the product was received at the time you made an order for the Service.</span></p>\
      <p><strong>&nbsp;</strong></p>\
      <p><span style="color: #ff6600;"><strong>Conditions for Using the Application</strong></span></p>\
      <p><span style="font-weight: 400;">You represent and warrant that you are an individual who has the right to enter into a binding agreement under the laws of the Republic of Indonesia and that you are at least 21 years old or married and not under guardianship. If not, Foodle has the right by law to cancel the agreement made with you. You further represent and guarantee that you have the right, authority and capacity to use our Application and also represent and guarantee that you will carry out and bind yourself to these Terms of Use and take the actions required in the Application.</span></p>\
      <p><span style="font-weight: 400;">Foodle has the right to collect and process your information, such as your full name, email, and cell phone number when you register and Foodle has the right to refuse your registration, if You do not provide personal information that serves completely and does not give consent to these terms of use, terms and conditions of this Privacy Policy.&nbsp;</span></p>\
      <p>&nbsp;</p>\
      <p><span style="color: #ff6600;"><strong>Privacy</strong></span></p>\
      <p><span style="font-weight: 400;">You guarantee that you provide accurate and complete information and agree to provide Foodle with any proof of identity that Foodle can reasonably request. If the personal information you provide to Foodle has changed, for example, if you change your e-mail address, telephone number, or if you wish to cancel your account, please update your details by sending your request to Foodle.</span></p>\
      <p><span style="font-weight: 400;">Foodle will apply these changes after you follow the required changes in order to change your personal data.</span></p>\
      <p><span style="font-weight: 400;">E-mails that have been registered in the Application cannot be used to create a new account.</span></p>\
      <p><span style="font-weight: 400;">You must follow the rules that are directed in the Application in order to enter yourself, the Application will provide you with a personal account with a password that you set yourself so that you can use the Application.</span></p>\
      <p><span style="font-weight: 400;">You must maintain the security and confidentiality of data relating to your account on the Application. In the event of disclosure of data relating to your account which results in any unauthorized or unauthorized use of your account or identity, you are required to notify Foodle about this so that Foodle can&nbsp;</span><span style="font-weight: 400;">cancel your account or take other actions that can be done and needed to done, if not, all actions using the Application will act as legitimate actions and you are responsible for the legal effects that arise as long as these actions have not been reported to Foodle.</span></p>\
      <p><span style="font-weight: 400;">You inform in detail to Foodle if you no longer have control over your account in the Application, for example your account is hacked or your cellphone is lost, so that Foodle can cancel your account in the proper way or take other actions that can be done and necessary to do, if not, any action using the application will be considered as a legitimate action and you are responsible for the legal consequences that arise as long as the action has not been notified to Foodle.</span></p>\
      <p><span style="font-weight: 400;">You promise that you will use the Application only for the purpose intended for obtaining the Service. You are not allowed to abuse or use the Application for fraudulent purposes or cause inconvenience to others or place fake orders.</span></p>\
      <p><span style="font-weight: 400;">Foodle has the authority to impose restrictions on you to further use the Application if you use the Application with an inappropriate or unauthorized device or for any other purpose other than the intended purpose for using this Application.</span></p>\
      <p><span style="font-weight: 400;">You understand, accept and agree that your use of the Foodle Application will also be subject to the Foodle Privacy Policy as may be changed from time to time. By using the Application, you also give your consent and are willing to be bound by the Foodle Privacy Policy.</span></p>\
      <p><span style="font-weight: 400;">By providing personal information / data to Foodle, you state that you have the right to provide Foodle with personal information / data that Foodle will use and you allow Foodle to provide your personal information / data to related third parties also.</span></p>\
      <p><span style="font-weight: 400;">Applications may not be used to search for services for things that are against the laws and norms that apply in society. You agree to maintain, indemnify and exempt Foodle, and Foodle is not responsible for the services used by you which may violate the applicable laws and regulations.</span></p>\
      <p><span style="font-weight: 400;">You must provide Foodle with accurate and complete information regarding the type, specification, quantity and / or any special characteristics of the product ordered and purchased.</span></p>\
      <p><span style="font-weight: 400;">Foodle has the right to reject your order if in Foodle\'s judgment, Foodle may not be able to deliver the product(s) or service(s). However, if you have deposited an amount of money for the use of the Service, you are entitled to request a refund of the amount that has been deposited if Foodle is unable to deliver the product.</span></p>\
      <p><span style="font-weight: 400;">Foodle has the right to refuse to accept your order if Foodle has reasonable reasons to suspect that you have, or by accepting an order from you, you will violate these Terms of Use or the applicable laws and regulations.</span></p>\
      <p><span style="font-weight: 400;">If based on Foodle\'s policy, Foodle provides gifts, vouchers, or various other forms of promotion ("Promos") which can be exchanged for benefits related to the use of the Application. You agree that you are only entitled to use the Promotion subject to all the conditions applicable in the Promo and will not abuse, duplicate, sell or transfer the Promo in any way. You also understand that the Promo cannot be exchanged for cash and can end on a certain date and time, even if you have not used it.</span></p>\
      <p><span style="font-weight: 400;">You acknowledge and understand that product prices displayed on the Service may change from time to time.</span></p>\
      <p>&nbsp;</p>\
      <p><span style="color: #ff6600;"><strong>Charging of Fees</strong></span></p>\
      <p><span style="font-weight: 400;">Download and / or access to this Application is free of charge. Foodle can introduce fees for downloading and / or accessing the Application at any time. Foodle will inform you about this accordingly so you can decide whether you want to continue downloading or accessing the Application or not. However, the internet connection required to use the Service and any associated costs incurred by using the Service are your own responsibility and are solely charged to you.</span></p>\
      <p><span style="font-weight: 400;">You agree that you will pay for the Services provided to you by Foodle in full before the product is delivered to you, unless Foodle agrees to provide you with the facility to be able to make payments after you receive the product.</span></p>\
      <p><span style="font-weight: 400;">The payment system can be done by transfer, e-money, and credit card must be made in Rupiah with payment instructions that Foodle will notify from time to time. Foodle also has the right to make changes or additions to the payment system in the Service from time to time if deemed necessary.</span></p>\
      <p><span style="font-weight: 400;">The fee for the Service includes any applicable taxes.</span></p>\
      <p>&nbsp;</p>\
      <p><span style="color: #ff6600;"><strong>Responsibilities of Foodle</strong></span></p>\
      <p><span style="font-weight: 400;">Foodle uses appropriate and reasonable information management and security to keep the application safe and free from interference from irresponsible parties. However, regardless of the maximum information management and security carried out, Foodle cannot guarantee that there will be no interruption of the service(s) and the application in the future.</span></p>\
      <p><span style="font-weight: 400;">Incompatible use of the internet and electronic communication may cause the Application to malfunction. Foodle is not responsible for delays, failures, damages or losses caused by these problems.</span></p>\
      <p>&nbsp;</p>\
      <p><span style="color: #ff6600;"><strong>Limitation of Liability</strong></span></p>\
      <p><span style="font-weight: 400;">Any claim against Foodle in any case by you, will be limited to the total amount that is apparently paid in writing by and / or owed to you when using the Service. In any case, Foodle will not be responsible to you or anyone for costs, interest, damage or loss of any kind or other form of value that is not written (including personal injury, emotional disturbance and loss of data, goods, income, profit, usage. or other economic benefits). Foodle will not be responsible for any loss, damage or injury that may be caused or caused by you or by any person on your behalf who has used the Service.</span></p>\
      <p><strong>&nbsp;</strong></p>\
      <p><span style="color: #ff6600;"><strong>Compensation</strong></span></p>\
      <p><span style="font-weight: 400;">By using this application, you agree that you will provide compensation and indemnify Foodle, its affiliates, and each of Foodle\'s officers, directors, commissioners, employees, lawyers and agents from and against any and all claims, costs, damages, losses, obligations and fees (including attorney\'s fees and fees) arising out of or in connection with: (a) violation of or non-compliance with any of the Terms of Use, Privacy Policy, or applicable laws and regulations, whether stated here or not or ( b) your violation of the rights of third parties related to the use of the Application that is not caused by Foodle, or (c) the use or misuse of the Application. This obligation to release and provide compensation will remain in effect even though your Terms of Use and use of the Application and Website have ended or been terminated by Foodle for any reason.</span></p>\
      <p><strong>&nbsp;</strong></p>\
      <p><span style="color: #ff6600;"><strong>Licensing</strong></span></p>\
      <p><span style="font-weight: 400;">You may not, in whole or in part, (i) copy, modify, imitate, adopt, adapt, translate, create derivative works of, distribute, license, trade, transfer, publicly display, reproduce, transmit, move, broadcast, decipher, damage, control, remove or dismantle any part or all of or in any other way that may exploit the Application, without the written consent of Foodle (ii) to license, sublicense, sell, resell, transfer, transfer , distribute or exploit commercially or make available to third parties the Application and / or software in any way; (iii) create and / or publish "frames" or "mirror" any software in the Application on other servers or wireless devices; (iv) reverse engineer or access Foodle software to (a) build competitive products or services, (b) build Applications using ideas, features, functions or graphics or application-like materials (v) create and publish media or scripts, including, but not limited to, web spiders, web crawlers, web robots, web ants, web indexers, bots, viruses or worms, or any program that may create an obstacle to the operation of the Application and / or the performance of the Application, (vi) using a robot, spider, or other&nbsp;</span><span style="font-weight: 400;">manual or automatic devices to retrieve data from within the Application, or in any way duplicate the contents of the Application (vii) publish, distribute or reproduce in any way copyright protected material, trademarks, or other proprietary information without obtaining the prior consent of the owner of the property rights, (viii) removing any copyright, trademark or other proprietary notices a contained in the Application. No license or right is granted to you with implications based on intellectual property rights owned or controlled by Foodle or Foodle\'s licensors, except for the license and rights expressly provided in these Terms of Use.</span></p>\
      <p><span style="font-weight: 400;">You (i) will not send spam, viral material, worms, trojan horses or&nbsp; other malicious computer code; (ii) will not post or store material that violates, immoral, threatening, defamatory, or illegal or unusual in nature, including but not limited to materials that are harmful to others or that violate the privacy rights of third parties; (iii) do not attempt to gain access without Foodle\'s consent to the Application or related systems or networks; and (iv) refrain from engaging in actions that may damage Foodle\'s reputation or are deemed to damage Foodle\'s reputation.</span></p>\
      <p><span style="font-weight: 400;">Foodle will have the right to investigate and prosecute any violations above as long as the law allows including involving law enforcement officials in doing this.&nbsp; Foodle has the right to monitor your access in the Application, to ensure compliance with these Terms of Use, or to comply with applicable regulations.</span></p>\
      <p><strong>&nbsp;</strong></p>\
      <p><span style="color: #ff6600;"><strong>Matters Related to Intellectual Property</strong></span></p>\
      <p><span style="font-weight: 400;">All content in the Application and Services, is protected by copyright, trademark, and other rights provided under the laws of the Republic of Indonesia. Without deviating from Foodle\'s rights based on applicable law or the Terms of Use, you are notified that any attempt or real violation of these provisions will result in the termination of all your rights in the Application and other law enforcement that can be implemented.</span></p>\
      <p><strong>&nbsp;</strong></p>\
      <p><span style="color: #ff6600;"><strong>Termination</strong></span></p>\
      <p><span style="font-weight: 400;">Foodle has the right to immediately suspend temporarily or permanently suspend the use of the Application if Foodle has reason to suspect that you have violated the provisions of these Terms of Use or applicable laws and regulations and orders of authorized officials. You have the right to choose to either temporarily or permanently use the Application at any time by canceling your account by calling our customer support or sending email to customersupport@foodle.id and permanently deleting the application from your device, thereby disabling the use of the Application.</span></p>\
      <p><strong>&nbsp;</strong></p>\
      <p><span style="color: #ff6600;"><strong>Representations and Warranties</strong></span></p>\
      <p><span style="font-weight: 400;">Foodle does not represent or guarantee that (a) the use of the Service and / or Application will be safe, timely, uninterrupted or error free or operate in combination with other hardware, software, systems or data or circumstances caused by divine power or force majeure beyond Foodle\'s control, such as floods, earthquakes, fires and hurricanes, conditions of war, riots, and / or government policies in the financial or monetary and economic sectors that directly affect the implementation of Applications and Services, (b ) The Application and Services will meet your needs or expectations, (c) any data stored will be accurate or reliable, (d) the quality of products, services, information or other materials purchased or obtained by you through the Application will fulfill the needs or your hope, (e) errors or flaws in the Application will be corrected, or (f) the application or server(s) the Application will be free from viruses or other dangerous components, or (g) the Application will track you or the vehicle used by Foodle in sending orders. The services provided to you are limited to an "as is" basis only. All conditions, representations and warranties, whether express, implied, required by law or otherwise, including, but not limited to, implied warranties regarding sale and purchase, fitness for a particular purpose, or non-infringement of third party rights, hereby excluded and excluded to the highest and maximum limits. You acknowledge and agree that all risks arising from your use of the Service remain solely and completely with you and you will not have the right to claim any compensation from the company.</span></p>\
      <p><strong>&nbsp;</strong></p>\
      <p><span style="color: #ff6600;"><strong>Others</strong></span></p>\
      <p><span style="font-weight: 400;">You cannot transfer your rights and obligations based on the Terms of Use and other provisions listed in the Application, without the prior written consent of Foodle. Foodle can transfer Foodle\'s rights based on the Terms of Use to other parties according to Foodle\'s policies. If there is a term based on the Terms of Use that is deemed invalid or unenforceable, either in whole or in part, based on statutory provisions, the term or part of the term will, to the extent, be deemed not part of these Terms of Use, but legality. , the validity or enforceability of other Terms of Use will remain valid.</span></p>\
      <p><span style="font-weight: 400;">These Terms of Use are governed by and interpreted under the laws of the Republic of Indonesia. Any and all disputes arising from the use of Foodle services will be governed by the exclusive jurisdiction of the Ternate&nbsp; District Court, Maluku Utara.</span></p>\
      <p>These Terms of Use can be changed, added, and reduced, revised, corrected from time to time. Foodle may or may not notify you via the Application and / or email regarding changes to the Terms of Use. Continuously deactivating the application after receiving this notification constitutes your approval and acceptance and commitment to the changes.</p>\
      <p><span style="font-weight: 400;">If you have further questions regarding these Terms of Use and Terms</span></p>\
      <p><span style="font-weight: 400;">of Use, then please contact us at:</span><span style="color: #ff6600;"><strong> customersupport@foodle.id</strong></span></p>\
      <p><strong>&nbsp;</strong></p>\
      <p><span style="color: #ff6600;"><strong>Terms and Conditions</strong></span></p>\
      <ol>\
      <li style="font-weight: 400;"><span style="font-weight: 400;">If the order has not been delivered within the specified time, you can contact our customer service team via e-mail customersupport@foodle.id to submit a complaint.</span></li>\
      <li style="font-weight: 400;"><span style="font-weight: 400;">Orders are delivered according to the address you put on the application during the checkout process.</span></li>\
      <li style="font-weight: 400;"><span style="font-weight: 400;">If you do not recieve the purchased product within the specified time, your ordered product(s) will be returned to the area specific Vendor warehouse.</span></li>\
      <li style="font-weight: 400;"><span style="font-weight: 400;">If after 36 hours of dispatching the product from our warehouse and if there is no confirmation from the buyer that the Items are not received by the buyer at the specified time then the items will be deemed received and a refund cannot be made.</span></li>\
      <li style="font-weight: 400;"><span style="font-weight: 400;">The buyer understands that every product that has been entered in the payment process cannot be cancelled for any reason.</span></li>\
      <li style="font-weight: 400;"><span style="font-weight: 400;">Foodle is not responsible to you for any damages of any kind arising from late delivery of products or products that are not successfully delivered due to buyer\'s fault.</span></li>\
      <li style="font-weight: 400;"><span style="font-weight: 400;">The Product(s) or Service(s) are provided by the Vendors of Foodle app platform and any dispute arising because of any reason will be directly dealt with by the Specific vendor who received the order.</span></li>\
      </ol>\
      <p><strong>&nbsp;</strong></p>\
      <p><span style="color: #ff6600;"><strong>Rejection</strong></span></p>\
      <p><span style="font-weight: 400;">You understand that at the time of ordering a product if it is not available for any reason, Foodle will notify you via e-mail or telephone listed in the Application that the product is not available and offer your willingness to wait or make a refund. Refund process takes no later than 10 (ten) working days after notification.</span></p>\
      <p><strong>&nbsp;</strong></p>\
      <p><span style="color: #ff6600;"><strong>Cancellation</strong></span></p>\
      <p><span style="font-weight: 400;">Once the product(s) or service(s) are purchased, you cannot cancel the product(s) or service(s) that has been purchased.</span></p>\
      <p><strong>&nbsp;</strong></p>\
      <p><span style="color: #ff6600;"><strong>Return Policy</strong></span></p>\
      <p><span style="font-weight: 400;">Foodle makes every effort to deliver products that are suitable for you, but if you are sent a product that you think is not suitable, you have the right to refuse when the product arrives at your order address by providing a valid and genuine reason why the product cannot be accepted.</span></p>\
      <p><span style="font-weight: 400;">However, if the product has been received as evidenced by proof of the recipient, then you cannot apply for a refund.</span></p>\
      <p><span style="font-weight: 400;">Therefore, you are obliged to check carefully that the product you receive is appropriate before the delivery person leaves your premises.</span></p>\
      <p><span style="font-weight: 400;">Refund policy for non-conforming products will be processed no later than 10 (ten) working days after you provide your bank account number to the Foodle team </span><strong>(email: <span style="color: #ff6600;">customersupport@foodle.id</span>)</strong><span style="font-weight: 400;"> for refund purposes.</span></p>\
      <h1>&nbsp;</h1>\
      <p><strong>Last Edited on 2020-Sep-06</strong></p>\
      <h1><br /><br /></h1>'
    }
    else {
      this.htmlStr = '<h2><strong>Ketentuan Penggunaan</strong></h2>\
      <p><strong>&nbsp;</strong></p>\
      <p><strong>Syarat Penggunaan</strong></p>\
      <p><span style="font-weight: 400;">SILAKAN PERIKSA SYARAT,&nbsp; KETENTUAN DAN KEBIJAKAN PRIVASI "Foodle"&nbsp; DENGAN SEKSAMA SEBELUM MENGUNDUH APLIKASI ATAU MENGGUNAKAN LAYANAN Foodle UNTUK PERTAMA KALI.</span></p>\
      <p><span style="font-weight: 400;">Dengan mengunduh, mengakses, dan / atau menggunakan Aplikasi Foodle ("Aplikasi"), Anda setuju bahwa Anda telah membaca, memahami dengan cermat, dan mematuhi persyaratan penggunaan ini ("Persyaratan Penggunaan"). Syarat Penggunaan ini merupakan perjanjian hukum antara Anda dan PT Perusahaan Indo Pasifik sehubungan dengan kunjungan Anda, akses dan penggunaan Layanan dan Aplikasi (masukan didefinisikan di bawah) dan situs web Foodle di www.foodle.id ("Situs Web").</span></p>\
      <p><span style="font-weight: 400;">JIKA ANDA TIDAK SETUJU DENGAN PERSYARATAN PENGGUNAAN BAIK BEBERAPA MAUPUN SELURUH PERSYARATAN INI, MAKA ANDA TIDAK PERLU MENGAKSES DAN MENGGUNAKAN LAYANAN APLIKASI.</span></p>\
      <p>&nbsp;</p>\
      <p><strong>Persyaratan umum</strong></p>\
      <ol>\
      <li><span style="font-weight: 400;"> Perusahaan Indo Pasifik adalah perusahaan yang didirikan berdasarkan hukum Republik Indonesia ("Foodle").</span></li>\
      </ol>\
      <p><span style="font-weight: 400;">Aplikasi ini merupakan aplikasi perangkat lunak yang berfungsi sebagai sarana pembelian produk yang disediakan dalam aplikasi. Aplikasi ini menawarkan informasi tentang layanan yang ditawarkan oleh Foodle. Jenis layanan yang disediakan Foodle melalui aplikasi adalah:</span></p>\
      <ul>\
      <li style="font-weight: 400;"><span style="font-weight: 400;">Pembelian produk yang terdaftar di Aplikasi;</span></li>\
      <li style="font-weight: 400;"><span style="font-weight: 400;">Pengiriman produk yang dibeli melalui Aplikasi;</span></li>\
      <li style="font-weight: 400;"><span style="font-weight: 400;">Layanan lain ialah layanan yang dapat ditambahkan Foodle dari waktu ke waktu. (selanjutnya disebut sebagai "Layanan").</span></li>\
      </ul>\
      <p><span style="font-weight: 400;">Foodle memiliki kebijakannya sendiri untuk menolak permintaan Anda untuk Layanan. Foodle juga memiliki kebijakannya sendiri untuk koreksi, menerima arahan yang diberikan oleh Aplikasi.</span></p>\
      <p><span style="font-weight: 400;">Foodle akan melakukan segala upaya bagi Anda untuk mendapatkan Layanan, tergantung pada data produk atau lokasi di mana produk itu diterima pada saat Anda melakukan pemesanan.</span></p>\
      <p><strong>&nbsp;</strong></p>\
      <p><strong>Ketentuan Penggunaan Aplikasi</strong></p>\
      <p><span style="font-weight: 400;">Anda menyatakan dan menjamin bahwa Anda adalah individu yang memiliki hak untuk membuat perjanjian yang mengikat berdasarkan hukum Republik Indonesia dan bahwa Anda setidaknya berusia 21 tahun atau sudah menikah dan tidak dalam perwalian. Jika tidak, Foodle berhak secara hukum untuk membatalkan perjanjian yang dibuat dengan Anda. Anda selanjutnya menyatakan dan menjamin bahwa Anda memiliki hak, wewenang dan kapasitas untuk menggunakan Aplikasi kami dan juga mewakili dan menjamin bahwa Anda akan melaksanakan dan mengikat diri Anda pada Ketentuan Penggunaan ini dan mengambil tindakan yang diperlukan dalam Aplikasi.</span></p>\
      <p><span style="font-weight: 400;">Foodle berhak mengumpulkan dan memproses informasi Anda, seperti nama lengkap, email, dan nomor ponsel saat Anda mendaftar dan Foodle berhak menolak pendaftaran Anda jika Anda tidak memberikan informasi pribadi yang berfungsi secara lengkap dan tidak memberikan menyetujui syarat penggunaan dan ketentuan Kebijakan Privasi ini.</span></p>\
      <p>&nbsp;</p>\
      <p><strong>Privasi</strong></p>\
      <p><span style="font-weight: 400;">Anda menjamin bahwa Anda memberikan informasi yang lengkap dan akurat serta setuju untuk memberikan Foodle bukti identitas apa pun yang dapat diminta secara wajar oleh Foodle. Jika informasi pribadi yang Anda berikan kepada Foodle telah berubah, misalnya, jika Anda mengubah alamat email, nomor telepon, atau jika Anda ingin membatalkan akun Anda, perbarui detail Anda dengan mengirimkan permintaan Anda ke Foodle.</span></p>\
      <p><span style="font-weight: 400;">Foodle akan menerapkan perubahan ini setelah Anda mengikuti perubahan yang diperlukan untuk mengubah data pribadi Anda.</span></p>\
      <p><span style="font-weight: 400;">Email yang telah terdaftar di Aplikasi tidak dapat digunakan untuk membuat akun baru.</span></p>\
      <p><span style="font-weight: 400;">Anda harus mengikuti aturan yang diarahkan dalam Aplikasi untuk masuk. Aplikasi akan memberi Anda akun pribadi dengan kata sandi yang Anda tentukan sendiri sehingga Anda dapat menggunakan Aplikasi.</span></p>\
      <p><span style="font-weight: 400;">Anda harus menjaga keamanan dan kerahasiaan data yang berkaitan dengan akun Anda pada Aplikasi. Dalam hal pengungkapan data yang berkaitan dengan akun Anda yang mengakibatkan penggunaan akun atau identitas Anda secara tidak sah, Anda wajib memberi tahu Foodle tentang hal ini sehingga Foodle dapat membatalkan akun Anda atau mengambil tindakan lain yang dapat dilakukan dan diperlukan untuk dilakukan. Jika tidak, semua tindakan yang menggunakan Aplikasi akan bertindak sebagai tindakan yang sah dan Anda bertanggung jawab atas akibat hukum yang timbul selama tindakan tersebut belum dilaporkan kepada Foodle.</span></p>\
      <p><span style="font-weight: 400;">Anda menginformasikan secara detail kepada Foodle jika Anda tidak lagi memiliki kendali atas akun Anda di Aplikasi, misalnya akun Anda diretas atau ponsel Anda hilang, sehingga Foodle dapat membatalkan akun Anda dengan cara yang tepat atau melakukan tindakan lain yang dapat dilakukan. Jika tidak, tindakan apa pun menggunakan aplikasi akan dianggap sebagai tindakan yang sah dan Anda bertanggung jawab atas konsekuensi hukum yang muncul selama tindakan tersebut belum diberitahukan kepada Foodle.</span></p>\
      <p><span style="font-weight: 400;">Anda berjanji bahwa Anda akan menggunakan Aplikasi hanya untuk tujuan yang dimaksudkan untuk mendapatkan Layanan. Anda tidak diperbolehkan untuk menyalahgunakan atau menggunakan Aplikasi untuk tujuan penipuan atau menyebabkan ketidaknyamanan kepada orang lain ataupun melakukan pemesanan palsu.</span></p>\
      <p><span style="font-weight: 400;">Foodle memiliki wewenang untuk memberlakukan batasan pada Anda untuk menggunakan Aplikasi lebih lanjut jika Anda menggunakan Aplikasi dengan perangkat yang tidak sesuai atau tidak sah atau untuk tujuan lain selain dari tujuan yang dimaksudkan untuk menggunakan Aplikasi ini.</span></p>\
      <p><span style="font-weight: 400;">Anda memahami, menerima, dan menyetujui akan penggunaan Anda atas Aplikasi Foodle juga akan patuh pada Kebijakan Privasi Foodle yang dapat berubah dari waktu ke waktu. Dengan menggunakan Aplikasi, Anda juga memberikan persetujuan dan bersedia untuk terikat oleh Kebijakan Privasi Foodle.</span></p>\
      <p><span style="font-weight: 400;">Dengan memberikan informasi / data pribadi kepada Foodle, Anda menyatakan bahwa Anda memiliki hak untuk memberikan informasi / data pribadi yang akan digunakan Foodle dan Anda mengizinkan Foodle untuk memberikan informasi / data pribadi Anda kepada pihak ketiga terkait juga.</span></p>\
      <p><span style="font-weight: 400;">Aplikasi tidak diperkenankan untuk mencari layanan atas hal-hal yang bertentangan dengan hukum dan norma yang berlaku di masyarakat. Anda setuju untuk memelihara, mengganti kerugian, dan membebaskan Foodle. Foodle tidak bertanggung jawab atas layanan yang Anda gunakan yang mungkin melanggar hukum dan peraturan yang berlaku.</span></p>\
      <p><span style="font-weight: 400;">Anda harus memberi Foodle informasi yang akurat dan lengkap mengenai jenis, spesifikasi, kuantitas dan / atau karakteristik khusus dari produk yang dipesan dan dibeli.</span></p>\
      <p><span style="font-weight: 400;">Foodle berhak untuk menolak pesanan Anda jika menurut penilaian, Foodle mungkin tidak dapat mengirimkan produk atau layanan tersebut. Namun, jika Anda telah menyetorkan sejumlah uang untuk penggunaan Layanan, Anda berhak untuk meminta pengembalian dana dari jumlah yang telah disimpan jika Foodle tidak dapat mengirimkan produk.</span></p>\
      <p><span style="font-weight: 400;">Foodle berhak menolak untuk menerima pesanan Anda jika Foodle memiliki alasan yang masuk akal untuk mencurigai bahwa Anda telah, atau menerima pesanan dari Anda. Anda tidak diperkenankan melanggar Ketentuan Penggunaan dan harus mematuhi hukum dan peraturan yang berlaku.</span></p>\
      <p><span style="font-weight: 400;">Jika berdasarkan kebijakan Foodle, Foodle memberikan hadiah, voucher, atau berbagai bentuk promosi ("Promo") lainnya yang dapat ditukar dengan keuntungan terkait penggunaan Aplikasi. Anda setuju bahwa Anda hanya berhak menggunakan Promosi dengan patuh pada semua ketentuan yang berlaku dalam Promo dan tidak akan menyalahgunakan, menggandakan, menjual atau mentransfer Promo dengan cara apa pun. Anda juga memahami bahwa Promo tidak dapat ditukar dengan uang tunai dan dapat berakhir pada tanggal dan waktu tertentu, meskipun Anda belum menggunakannya.</span></p>\
      <p><span style="font-weight: 400;">Anda mengetahui dan memahami bahwa harga produk yang ditampilkan pada Layanan dapat berubah dari waktu ke waktu.</span></p>\
      <p><strong>Pengenaan Biaya</strong></p>\
      <p><span style="font-weight: 400;">Download dan / atau akses ke Aplikasi ini gratis. Foodle dapat memperkenalkan biaya untuk mengunduh dan / atau mengakses Aplikasi kapan saja. Foodle akan memberitahu Anda tentang hal ini sehingga Anda dapat memutuskan apakah Anda ingin melanjutkan untu mengakses Aplikasi atau tidak. Namun demikian, koneksi internet yang diperlukan untuk menggunakan Layanan dan semua biaya terkait yang timbul karena menggunakan Layanan adalah tanggung jawab Anda sendiri dan sepenuhnya dibebankan kepada Anda.</span></p>\
      <p><span style="font-weight: 400;">Anda setuju bahwa Anda akan membayar Layanan yang diberikan kepada Anda oleh Foodle secara penuh sebelum produk dikirimkan kepada Anda, kecuali Foodle setuju untuk memberi Anda fasilitas untuk dapat melakukan pembayaran setelah Anda menerima produk.&nbsp;</span></p>\
      <p><span style="font-weight: 400;">Sistem pembayaran dapat dilakukan dengan transfer, e-money, dan kartu kredit harus dilakukan dalam Rupiah dengan instruksi pembayaran yang akan diberitahukan oleh Foodle. Foodle juga berhak untuk melakukan perubahan atau penambahan pada sistem pembayaran di Layanan dari waktu ke waktu jika dianggap perlu. Biaya Layanan termasuk pajak yang berlaku.</span></p>\
      <p><strong>Tanggung jawab Foodle</strong></p>\
      <p><span style="font-weight: 400;">Foodle menggunakan manajemen dan keamanan informasi yang wajar dan sesuai untuk menjaga aplikasi tetap aman dan bebas dari gangguan dari pihak yang tidak bertanggung jawab. Namun, terlepas dari manajemen informasi dan keamanan maksimum yang dilakukan, Foodle tidak dapat menjamin bahwa tidak akan ada gangguan layanan dan aplikasi di masa mendatang.</span></p>\
      <p><span style="font-weight: 400;">Penggunaan internet dan komunikasi elektronik yang tidak sesuai dapat menyebabkan Aplikasi tidak berfungsi. Foodle tidak bertanggung jawab atas keterlambatan, kegagalan, kerusakan atau kerugian yang disebabkan oleh masalah ini.</span></p>\
      <p><strong>Pembatasan Tanggung Jawab</strong></p>\
      <p><span style="font-weight: 400;">Setiap klaim terhadap Foodle dalam hal apapun oleh Anda, akan dibatasi pada jumlah total yang dibayar secara tertulis oleh dan / atau terutang kepada Anda ketika menggunakan Layanan. Bagaimanapun, Foodle tidak akan bertanggung jawab kepada Anda atau siapa pun atas biaya, bunga, kerusakan, atau kerugian dalam bentuk apa pun atau bentuk nilai lain yang tidak tertulis (termasuk cedera pribadi, gangguan emosional, dan hilangnya data, barang, pendapatan, keuntungan, penggunaan, atau manfaat ekonomi lainnya). Foodle tidak akan bertanggung jawab atas kehilangan, kerusakan, atau cedera yang mungkin disebabkan oleh Anda atau oleh siapa pun atas nama Anda yang telah menggunakan Layanan.</span></p>\
      <p><strong>&nbsp;</strong></p>\
      <p><strong>Kompensasi</strong></p>\
      <p><span style="font-weight: 400;">Dengan menggunakan aplikasi ini, Anda setuju bahwa Anda akan memberikan kompensasi dan mengganti rugi Foodle, dan afiliasinya, untuk masing-masing pejabat, direktur, komisaris, karyawan, pengacara dan agen Foodle dan terhadap setiap dan semua klaim, biaya, kerusakan, kerugian, kewajiban dan biaya (termasuk biaya dan ongkos pengacara) yang timbul dari atau sehubungan dengan: (a) pelanggaran atau ketidakpatuhan terhadap Syarat Penggunaan, Kebijakan Privasi, atau hukum dan peraturan yang berlaku, baik yang dinyatakan di sini atau tidak, atau (b) pelanggaran Anda terhadap hak pihak ketiga terkait dengan penggunaan Aplikasi yang tidak disebabkan oleh Foodle, atau (c) penggunaan atau penyalahgunaan Aplikasi. Kewajiban untuk melepaskan dan memberikan kompensasi ini akan tetap berlaku meskipun Syarat Penggunaan dan penggunaan Aplikasi dan Situs Web Anda telah berakhir atau dihentikan oleh Foodle karena alasan apa pun.</span></p>\
      <p><strong>&nbsp;</strong></p>\
      <p><strong>Pemberian Lisensi</strong></p>\
      <p><span style="font-weight: 400;">Anda tidak boleh, secara keseluruhan atau sebagian, (i) menyalin, memodifikasi, meniru, mengadopsi, mengadaptasi, menerjemahkan, membuat karya turunan, mendistribusikan, melisensikan, memperdagangkan, mentransfer, menampilkan secara publik, mereproduksi, mengirimkan, memindahkan, menyiarkan, menguraikan, merusak, mengontrol, menghapus atau membongkar sebagian atau semua atau dengan cara lain yang dapat mengeksploitasi Aplikasi, tanpa persetujuan tertulis dari Foodle (ii) untuk melisensikan, mensublisensikan, menjual, mentransfer, mendistribusikan atau mengeksploitasi secara komersial atau menyediakan Aplikasi dan / atau perangkat lunak kepada pihak ketiga dengan cara apapun; (iii) membuat dan / atau menerbitkan "bingkai" atau "mencerminkan" perangkat lunak apapun dalam Aplikasi pada server atau perangkat nirkabel lain; (iv) merekayasa balik atau mengakses perangkat lunak Foodle untuk (a) membangun kompetitif produk atau layanan (b) yang membangun Aplikasi menggunakan ide, fitur, fungsi atau grafik atau materi serupa aplikasi (v) membuat dan menerbitkan media atau skrip, namun tidak terbatas pada, spider web, crawler web, robot web, semut web, pengindeks web, bot, virus atau worm, atau program apa pun yang dapat menghalangi pengoperasian Aplikasi dan / atau kinerja Aplikasi, (vi) menggunakan robot, spider, atau perangkat manual atau otomatis lainnya untuk mengambil data dari dalam Aplikasi, atau dengan cara apapun menggandakan konten Aplikasi (vii) menerbitkan, mendistribusikan, atau bereproduksi dengan cara apapun materi yang dilindungi hak cipta, merek dagang, atau informasi kepemilikan lainnya tanpa memperoleh persetujuan sebelumnya dari pemilik hak milik, (viii) menghapus hak cipta, merek dagang atau pemberitahuan kepemilikan lainnya yang terkandung dalam Aplikasi. Tidak ada lisensi atau hak yang diberikan kepada Anda dengan implikasi berdasarkan hak kekayaan intelektual yang dimiliki atau dikendalikan oleh Foodle atau pemberi lisensi Foodle, kecuali untuk lisensi dan hak yang secara tegas diberikan dalam Ketentuan Penggunaan ini.</span></p>\
      <p><span style="font-weight: 400;">Anda (i) tidak akan mengirim spam, materi viral, worm, trojan horse, atau kode komputer berbahaya lainnya; (ii) tidak akan memposting atau menyimpan materi yang melanggar, tidak bermoral, mengancam, memfitnah, atau ilegal atau tidak biasa, termasuk namun tidak terbatas pada materi yang berbahaya bagi orang lain atau yang melanggar hak privasi pihak ketiga; (iii) jangan mencoba untuk mendapatkan akses tanpa persetujuan Foodle ke Aplikasi atau sistem atau jaringan terkait; dan (iv) menahan diri untuk tidak melakukan tindakan yang dapat merusak reputasi Foodle atau dianggap merusak reputasi Foodle.</span></p>\
      <p><span style="font-weight: 400;">Foodle akan memiliki hak untuk menyelidiki dan menuntut setiap pelanggaran di atas selama hukum mengizinkan termasuk melibatkan aparat penegak hukum dalam melakukan hal tersebut. Foodle memiliki hak untuk memantau&nbsp;</span><span style="font-weight: 400;">akses Anda dalam Aplikasi, untuk memastikan kepatuhan dengan Ketentuan Penggunaan ini, atau untuk mematuhi peraturan yang berlaku.</span></p>\
      <p><strong>&nbsp;</strong></p>\
      <p><strong>Hal-hal yang Terkait dengan Kekayaan Intelektual</strong></p>\
      <p><span style="font-weight: 400;">Semua konten dalam Aplikasi dan Layanan dilindungi oleh hak cipta, merek dagang, dan hak-hak lain yang diatur berdasarkan hukum Republik Indonesia.</span></p>\
      <p><span style="font-weight: 400;">Tanpa menyimpang dari hak Foodle berdasarkan hukum yang berlaku atau Ketentuan Penggunaan, Anda diberi tahu bahwa setiap upaya atau pelanggaran nyata terhadap ketentuan ini akan mengakibatkan penghentian semua hak Anda dalam Aplikasi dan penegakan hukum lainnya yang dapat diterapkan.</span></p>\
      <p><strong>&nbsp;</strong></p>\
      <p><strong>Penghentian</strong></p>\
      <p><span style="font-weight: 400;">Foodle berhak untuk segera menangguhkan sementara atau selamanya penggunaan Aplikasi jika Foodle memiliki alasan untuk mencurigai bahwa Anda telah melanggar ketentuan Syarat Penggunaan ini atau hukum dan peraturan yang berlaku serta perintah pejabat yang berwenang. Anda memiliki hak untuk memilih baik untuk sementara atau secara permanen menggunakan Aplikasi setiap saat dengan membatalkan akun Anda dengan menghubungi customer support kami atau mengirim email ke customersupport@foodle.id dan secara permanen menghapus aplikasi dari perangkat Anda, sehingga menonaktifkan penggunaan aplikasi.</span></p>\
      <p>&nbsp;</p>\
      <p><strong>Pernyataan dan Jaminan</strong></p>\
      <p><span style="font-weight: 400;">Foodle tidak menyatakan atau menjamin bahwa (a) penggunaan Layanan dan / atau Aplikasi akan aman, tepat waktu, tidak terputus atau bebas dari kesalahan atau beroperasi dalam kombinasi dengan perangkat keras, perangkat lunak, sistem atau data atau keadaan lain yang disebabkan oleh ilahi. power atau force majeure di luar kendali Foodle, seperti banjir, gempa bumi, kebakaran dan angin topan, kondisi perang, kerusuhan, dan / atau kebijakan pemerintah di bidang keuangan atau moneter dan ekonomi yang secara langsung mempengaruhi implementasi Aplikasi dan Layanan, (b) Aplikasi dan Layanan akan memenuhi kebutuhan atau harapan Anda, (c) setiap data yang disimpan akan akurat atau dapat diandalkan, (d) kualitas produk, layanan, informasi atau materi lain yang Anda beli atau peroleh melalui Aplikasi akan memenuhi kebutuhan atau harapan anda, (e) kesalahan atau kekurangan dalam Aplikasi akan diperbaiki, atau (f) aplikasi atau server Aplikasi akan bebas dari virus atau komponen berbahaya lainnya s, atau (g) Aplikasi akan melacak Anda atau kendaraan yang digunakan oleh Foodle dalam mengirimkan pesanan.&nbsp;</span></p>\
      <p><span style="font-weight: 400;">Layanan yang diberikan kepada Anda terbatas hanya pada dasar "sebagaimana adanya". Semua kondisi, representasi dan jaminan, baik tersura maupun&nbsp;</span><span style="font-weight: 400;">tersirat, diwajibkan oleh hukum atau sebaliknya, termasuk, namun tidak terbatas pada jaminan tersirat mengenai penjualan dan pembelian, kesesuaian untuk tujuan tertentu, atau non-pelanggaran hak pihak ketiga, dengan ini dikecualikan dan dikecualikan sampai batas tertinggi dan maksimum. Anda mengakui dan setuju bahwa semua risiko yang timbul dari penggunaan Anda atas Layanan tetap sepenuhnya dan sepenuhnya menjadi tanggung jawab Anda dan Anda tidak berhak untuk mengklaim kompensasi apa pun dari perusahaan.</span></p>\
      <p>&nbsp;</p>\
      <p><strong>Lainnya</strong></p>\
      <p><span style="font-weight: 400;">Anda tidak dapat mengalihkan hak dan kewajiban Anda berdasarkan Ketentuan Penggunaan dan ketentuan lain yang tercantum dalam Aplikasi, tanpa persetujuan tertulis sebelumnya dari Foodle. Foodle dapat mengalihkan hak Foodle berdasarkan Ketentuan Penggunaan kepada pihak lain sesuai dengan kebijakan Foodle. Jika ada istilah berdasarkan Ketentuan Penggunaan yang dianggap tidak sah atau tidak dapat dilaksanakan, baik seluruhnya atau sebagian, berdasarkan ketentuan perundang-undangan, istilah atau sebagian dari istilah tersebut akan dianggap bukan bagian dari Ketentuan ini. Penggunaan, tetapi legalitas. , validitas atau keberlakuan Ketentuan Penggunaan lainnya akan tetap valid.</span></p>\
      <p><span style="font-weight: 400;">Ketentuan Penggunaan ini diatur oleh dan ditafsirkan berdasarkan hukum Republik Indonesia. Setiap dan semua sengketa yang timbul dari penggunaan layanan Foodle akan diatur oleh yurisdiksi eksklusif Pengadilan Negeri Ternate, Maluku Utara.</span></p>\
      <p><span style="font-weight: 400;">Ketentuan Penggunaan ini dapat diubah, ditambahkan, dan dikurangi, direvisi, diperbaiki dari waktu ke waktu. Foodle mungkin atau mungkin tidak memberi tahu Anda melalui Aplikasi dan / atau email tentang perubahan Syarat Penggunaan. Menonaktifkan aplikasi secara terus-menerus setelah menerima pemberitahuan ini merupakan persetujuan dan penerimaan Anda serta komitmen terhadap perubahan.</span></p>\
      <p><span style="font-weight: 400;">Jika Anda memiliki pertanyaan lebih lanjut tentang Ketentuan Penggunaan silakan hubungi kami di:</span> <a href="mailto:customersupport@foodle.id"><strong>customersupport@foodle.id</strong></a></p>\
      <p><strong>&nbsp;</strong></p>\
      <p><strong>Syarat dan Ketentuan</strong></p>\
      <ol>\
      <li style="font-weight: 400;"><span style="font-weight: 400;">Jika pesanan belum terkirim dalam waktu yang ditentukan, Anda dapat menghubungi tim layanan pelanggan kami melalui email </span><strong>customersupport@foodle.id</strong><span style="font-weight: 400;"> untuk mengajukan keluhan.</span></li>\
      <li style="font-weight: 400;"><span style="font-weight: 400;">Pesanan akan dikirimkan sesuai dengan alamat yang Anda masukkan pada aplikasi pada proses checkout.</span></li>\
      <li style="font-weight: 400;"><span style="font-weight: 400;">Jika Anda tidak menerima produk yang dibeli dalam waktu yang ditentukan, produk yang Anda pesan akan dikembalikan ke gudang Vendor tertentu di area tersebut.</span></li>\
      <li style="font-weight: 400;"><span style="font-weight: 400;">Jika setelah 36 jam pengiriman produk dari gudang kami dan jika tidak ada konfirmasi dari pembeli bahwa Barang tidak diterima oleh pembeli pada waktu yang ditentukan maka barang tersebut akan dianggap telah diterima dan refund tidak dapat dilakukan.</span></li>\
      <li style="font-weight: 400;"><span style="font-weight: 400;">Pembeli memahami bahwa setiap produk yang sudah masuk dalam proses pembayaran tidak dapat dibatalkan dengan alasan apapun.</span></li>\
      <li style="font-weight: 400;"><span style="font-weight: 400;">Foodle tidak bertanggung jawab kepada Anda atas kerusakan apa pun yang timbul dari keterlambatan pengiriman produk atau produk yang tidak berhasil dikirim karena kesalahan pembeli.</span><span style="font-weight: 400;">Produk atau Layanan disediakan oleh vendor platform aplikasi Foodle dan setiap perselisihan yang timbul karena alasan apapun akan ditangani secara langsung oleh vendor Tertentu yang menerima pesanan.</span></li>\
      </ol>\
      <p><strong>Penolakan</strong></p>\
      <p><span style="font-weight: 400;">Anda memahami jika pada saat memesan produk tidak tersedia karena alasan apapun, Foodle akan memberitahu Anda melalui email atau telepon yang tercantum dalam Aplikasi bahwa produk tidak tersedia dan menawarkan kesediaan Anda untuk menunggu atau melakukan pengembalian uang. Proses pengembalian dana membutuhkan waktu paling lambat 10 (sepuluh) hari kerja setelah pemberitahuan.</span></p>\
      <p><strong>Pembatalan</strong></p>\
      <p><span style="font-weight: 400;">Setelah produk atau layanan dibeli, Anda tidak dapat membatalkan produk atau layanan yang telah dibeli.</span></p>\
      <p><strong>Kebijakan Pengembalian</strong></p>\
      <p><span style="font-weight: 400;">Foodle berusaha semaksimal mungkin untuk mengirimkan produk yang sesuai untuk Anda, tetapi jika Anda dikirimi produk yang menurut Anda tidak sesuai, Anda memiliki hak untuk menolak saat produk tersebut sampai di alamat&nbsp; pesanan Anda dengan memberikan alasan yang valid mengapa produk tersebut tidak dapat diterima.</span></p>\
      <p><span style="font-weight: 400;">Namun, jika produk sudah diterima yang dibuktikan dengan bukti penerima, maka Anda tidak dapat mengajukan pengembalian uang.</span></p>\
      <p><span style="font-weight: 400;">Oleh karena itu, Anda wajib memeriksa dengan cermat apakah produk yang Anda terima sudah sesuai sebelum kurir atau pengantar meninggalkan tempat Anda.</span></p>\
      <p><span style="font-weight: 400;">Kebijakan refund untuk produk yang tidak sesuai akan diproses selambat-lambatnya 10 (sepuluh) hari kerja setelah Anda memberikan nomor akun Anda kepada tim Foodle </span><strong>(email: customersupport@foodle.id)</strong><span style="font-weight: 400;"> untuk keperluan refund.</span></p>\
      <p>&nbsp;</p>\
      <p><strong>Terakhir Diedit pada 2020-Sep-09</strong></p>';
    }
  }
}
